### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by guilherme6191** [uzyn/react-webpack-airbnbjs-boilerplate#1]
Hey, good work.

I noticed that `"babel-preset-es2015"` is missing in the package.json file.

**Comment by uzyn** [comment]
Thanks @guilherme6191 
Would you like to submit a pull request?

**Comment by guilherme6191** [comment]
Sure thing.

I inserted the last version of the package. I think it's ok to use it. 
Let me know if it should be another version though.

**Comment by uzyn** [comment]
#2 merged.
Thanks.
